version: '3'
services: 

    authentication:
        build: ./auth-service
        volumes:
            - ./auth-service:/usr/src/app
        ports: 
            - 3000:3000
     

    interface:
        build: ./interface-service
        volumes:
            - ./interface-service:/usr/src/app
        ports:
            - 8000:8000
        

    global-chat:
        build: ./global-chat-service
        volumes:
            - ./global-chat-service:/usr/src/app
        ports:
            - 7000:7000
        

    post:
        build: ./post-service
        volumes:
            - ./post-service:/usr/src/app
        ports:
            - 4000:4000
        
            
    